# Site settings
title: YtnomSnrub
description: ytnomsnrub.github.io
repository: YtnomSnrub/ytnomsnrub.github.io
github_username: YtnomSnrub

# Dir for sass files
sass:
  sass_dir: _scss


# Pages to appear in the tabs row under the title
header_pages: 
- index.md
- haikubot/index.md

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
# Analytics
google_analytics: UA-105356258-3
google_optimise: GTM-M396ZDN

github: [metadata]
