# Site settings
title: YtnomSnrub
description: ytnomsnrub.github.io
repository: YtnomSnrub/ytnomsnrub.github.io
github_username: YtnomSnrub

# Dir for sass files
sass:
  sass_dir: _scss

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

github: [metadata]